include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    unused_field: ignore
    unused_element: ignore
    argument_type_not_assignable: ignore
    invalid_assignment: ignore

linter:
  rules:
    public_member_api_docs: false
    prefer_asserts_with_message: false
    comment_references: false
    cascade_invocations: false
